from typing import TypedDict, Annotated, List, Any
import operator

class AgentState(TypedDict):
    """
    Represents the state of our autonomous research agent.
    This state object is passed from node to node in the LangGraph.
    """
    
    # The original query from the user
    query: str
    
    # The plan generated by the Planner Node (a list of distinct search sub-queries)
    search_plan: List[str]
    
    # Annotated with operator.add means that when a node returns 'documents', 
    # LangGraph will append them to the existing list rather than overwriting it.
    documents: Annotated[List[dict[str, Any]], operator.add]
    
    # The current draft of the research report
    draft: str
    
    # Feedback from the Critic Node. If there are notes, we might need to search again or rewrite.
    revision_notes: str
    
    # A counter to prevent infinite loops (e.g. going back and forth between Critic and Search forever)
    loop_count: int
